import { describe, it, expect } from "vitest";
import { generatePdf, layoutDocument, pdfToBytes } from "../pdf.js";
import type { PdfDoc } from "../types.js";

const sample: PdfDoc = {
  title: "Quarterly Report",
  blocks: [
    { type: "heading", text: "Quarterly Report", level: 1 },
    { type: "text", text: "Generated by react-pdf-generator." },
    {
      type: "table",
      header: ["Metric", "Value"],
      rows: [
        ["Revenue", "120000"],
        ["Profit", "32000"],
      ],
    },
  ],
};

describe("generatePdf", () => {
  it("starts with the PDF header and ends with EOF", () => {
    const pdf = generatePdf(sample);
    expect(pdf.startsWith("%PDF-1.4")).toBe(true);
    expect(pdf.trimEnd().endsWith("%%EOF")).toBe(true);
  });

  it("contains the document text in the content stream", () => {
    const pdf = generatePdf(sample);
    expect(pdf).toContain("Quarterly Report");
    expect(pdf).toContain("Generated by react-pdf-generator.");
    expect(pdf).toContain("Revenue");
    expect(pdf).toContain("120000");
  });

  it("includes a valid xref and trailer structure", () => {
    const pdf = generatePdf(sample);
    expect(pdf).toContain("xref");
    expect(pdf).toContain("trailer");
    expect(pdf).toContain("/Root 1 0 R");
    expect(pdf).toMatch(/startxref\n\d+/);
  });

  it("stores the title in the Info dictionary", () => {
    const pdf = generatePdf(sample);
    expect(pdf).toMatch(/\/Title \(Quarterly Report\)/);
  });

  it("escapes parentheses in text so the PDF stays well-formed", () => {
    const pdf = generatePdf({ blocks: [{ type: "text", text: "net (loss)" }] });
    expect(pdf).toContain("net \\(loss\\)");
  });

  it("declares exactly one page for short content", () => {
    const pdf = generatePdf(sample);
    expect(pdf).toContain("/Type /Pages /Count 1");
  });

  it("xref offsets point at real object markers", () => {
    const pdf = generatePdf(sample);
    // Object 1 should appear at the offset declared right after the free entry.
    const match = pdf.match(/xref\n0 \d+\n0000000000 65535 f \n(\d{10}) 00000 n /);
    expect(match).not.toBeNull();
    const offset = Number(match![1]);
    expect(pdf.slice(offset, offset + 7)).toBe("1 0 obj");
  });
});

describe("pagination", () => {
  it("splits long content across multiple pages", () => {
    const blocks = Array.from({ length: 200 }, (_, i) => ({
      type: "text" as const,
      text: `Line number ${i} with some content to fill the page.`,
    }));
    const { pages } = layoutDocument({ blocks });
    expect(pages.length).toBeGreaterThan(1);
    const pdf = generatePdf({ blocks });
    expect(pdf).toContain(`/Type /Pages /Count ${pages.length}`);
  });

  it("places text within the page's vertical bounds", () => {
    const { pages, height } = layoutDocument(sample);
    for (const ops of pages) {
      for (const op of ops) {
        expect(op.y).toBeGreaterThanOrEqual(0);
        expect(op.y).toBeLessThanOrEqual(height);
      }
    }
  });
});

describe("pdfToBytes", () => {
  it("produces bytes whose first four match %PDF", () => {
    const bytes = pdfToBytes(generatePdf(sample));
    expect(Array.from(bytes.slice(0, 4))).toEqual(
      ["%", "P", "D", "F"].map((c) => c.charCodeAt(0)),
    );
  });

  it("length equals the source string length", () => {
    const pdf = generatePdf(sample);
    expect(pdfToBytes(pdf).length).toBe(pdf.length);
  });
});
